server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mapstruct_example
    username: postgres
    password: root123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

